// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmSDEbD4MtVa3VpMZb-ja5p8AowHnFc3Q',
    appId: '1:796843944530:web:521a14b75b856308ebcd8b',
    messagingSenderId: '796843944530',
    projectId: 'fanatic-flutter',
    authDomain: 'fanatic-flutter.firebaseapp.com',
    storageBucket: 'fanatic-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjHtqBlkRCUaVXU7dWcTw009gOP698J6E',
    appId: '1:796843944530:android:6d90cc7558789212ebcd8b',
    messagingSenderId: '796843944530',
    projectId: 'fanatic-flutter',
    storageBucket: 'fanatic-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAz1L51SjpWICraegHnJN_elFg7hSg9-i8',
    appId: '1:796843944530:ios:1703ee102503d2e9ebcd8b',
    messagingSenderId: '796843944530',
    projectId: 'fanatic-flutter',
    storageBucket: 'fanatic-flutter.appspot.com',
    iosBundleId: 'com.example.fanatic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAz1L51SjpWICraegHnJN_elFg7hSg9-i8',
    appId: '1:796843944530:ios:27ab65f6caaf3dd0ebcd8b',
    messagingSenderId: '796843944530',
    projectId: 'fanatic-flutter',
    storageBucket: 'fanatic-flutter.appspot.com',
    iosBundleId: 'com.example.fanatic.RunnerTests',
  );
}
